### ISSUE TITLE
Dokuwiki updates

### ISSUE THREAD

**Issue by Ryonez** [mprasil/dronelab#1]
Please forgive me, but I've spent about half an hour trying to find some contact information for you, and this is the best I can think of atm.

Long story short, the dokuwiki docker image is out of date. I'm not sure how long it has been, but there is a hotfix that I'm being notified of. Could you please update it?

And would it be possible for to open an issue board [here](https://bitbucket.org/mprasil/docker_dokuwiki/src/master/) or somewhere else? That way we have a place to properly contact you for issues.

Cheers.

**Comment by mprasil** [comment]
Hi, the project is hosted [on bitbucket](https://bitbucket.org/mprasil/docker_dokuwiki/). I enabled [issues tracker](https://bitbucket.org/mprasil/docker_dokuwiki/issues) there now. So feel free to report it there and I'll have a look. Long term I probably want to migrate to Gitlab or Github or anything more sane than Bitbucket :smile: but it's kind of complicated with automated builds on docker hub.

Thanks for going the extra mile and reaching out.
